//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grimoire.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grimoire.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;txtMonster&quot;:&quot;Monster (*  = random)&quot;,&quot;txtKillFMon&quot;:&quot;Monster (* = random)&quot;,&quot;txtKillFItem&quot;:&quot;Item name&quot;,&quot;txtKillFQ&quot;:&quot;Quantity (* = any)&quot;,&quot;txtPacket&quot;:&quot;%xt%zm%.........&quot;,&quot;txtPlayer&quot;:&quot;Player name&quot;,&quot;txtAuthor&quot;:&quot;Author&quot;,&quot;txtDescription&quot;:&quot;Description&quot;,&quot;txtJoin&quot;:&quot;battleon-1e99&quot;,&quot;txtJoinCell&quot;:&quot;Enter&quot;,&quot;txtJoinPad&quot;:&quot;Spawn&quot;,&quot;txtCell&quot;:&quot;Cell&quot;,&quot;txtPad&quot;:&quot;Pad&quot;,&quot;txtItem&quot;:&quot;Item name&quot;,&quot;txtSwapBank&quot;:&quot;Bank item name&quot;,&quot;txtSwapInv&quot;:&quot;Inventory item name&quot;,&quot;txtWhitelist&quot;:&quot;Item name&quot;,&quot;txtLabel&quot;:&quot;Label name&quot;}.
        /// </summary>
        internal static string defaulttext {
            get {
                return ResourceManager.GetString("defaulttext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] grimoire {
            get {
                object obj = ResourceManager.GetObject("grimoire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;$type&quot;:&quot;System.Collections.Generic.List`1[[Grimoire.Botting.Commands.Misc.Statements.StatementCommand, Grimoire]], mscorlib&quot;,&quot;$values&quot;:[{&quot;$type&quot;:&quot;Grimoire.Botting.Commands.Misc.Statements.CmdCellIs, Grimoire&quot;,&quot;Tag&quot;:&quot;Map&quot;,&quot;Text&quot;:&quot;Cell is&quot;,&quot;Description1&quot;:&quot;Cell&quot;},{&quot;$type&quot;:&quot;Grimoire.Botting.Commands.Misc.Statements.CmdCellIsNot, Grimoire&quot;,&quot;Tag&quot;:&quot;Map&quot;,&quot;Text&quot;:&quot;Cell is not&quot;,&quot;Description1&quot;:&quot;Cell&quot;},{&quot;$type&quot;:&quot;Grimoire.Botting.Commands.Misc.Statements.CmdGoldGreaterThan, Grimoire&quot;,&quot;Tag&quot;:&quot;This player&quot;,&quot;Text&quot;:&quot;Gold is [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statementcmds {
            get {
                return ResourceManager.GetString("statementcmds", resourceCulture);
            }
        }
    }
}
